from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from milknado.domains.common.types import MikadoNode, RebaseResult


class GitPort(Protocol):
    def create_worktree(self, path: Path, branch: str) -> Path: ...
    def remove_worktree(self, path: Path) -> None: ...
    def rebase(self, worktree: Path, onto: str) -> RebaseResult: ...
    def current_branch(self) -> str: ...
    def commit_all(self, worktree: Path, message: str) -> None: ...


class CrgPort(Protocol):
    def ensure_graph(self, project_root: Path) -> None: ...
    def get_impact_radius(self, files: list[str]) -> dict[str, Any]: ...
    def get_architecture_overview(self) -> dict[str, Any]: ...


class RalphPort(Protocol):
    def create_run(
        self,
        agent: str,
        ralph_dir: Path,
        ralph_file: Path,
        commands: list[str],
        quality_gates: list[str],
    ) -> Any: ...
    def start_run(self, run_id: str) -> None: ...
    def stop_run(self, run_id: str) -> None: ...
    def list_runs(self) -> list[Any]: ...
    def get_run(self, run_id: str) -> Any | None: ...
    def wait_for_next_completion(
        self, active_run_ids: set[str],
    ) -> tuple[str, bool]: ...
    def generate_ralph_md(
        self,
        node: MikadoNode,
        context: str,
        quality_gates: list[str],
        output_path: Path,
    ) -> Path: ...
