from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Literal, Protocol

from milknado.domains.common.flavor_codec import Gate
from milknado.domains.common.types import MikadoNode, RebaseResult


@dataclass(frozen=True)
class ProgressEvent:
    run_id: str
    work: int
    total: int
    message: str = ""


@dataclass(frozen=True)
class VerifySpecResult:
    outcome: Literal["done", "gaps"]
    goal_delta: str | None = None


@dataclass(frozen=True)
class GraphExecutionSnapshot:
    """Atomic graph facts required to compute execution availability."""

    root: MikadoNode | None
    nodes: tuple[MikadoNode, ...]
    ready_node_ids: tuple[int, ...]
    running_node_ids: tuple[int, ...]
    parallel_conflicts: tuple[tuple[int, int, tuple[str, ...]], ...]


class GitPort(Protocol):
    def create_worktree(self, path: Path, branch: str) -> Path: ...
    def branch_exists(self, branch: str) -> bool: ...
    def remove_worktree(self, path: Path, target: str = "HEAD") -> None: ...
    def worktree_teardown_blocker(self, path: Path, target: str = "HEAD") -> str | None: ...
    def force_remove_worktree(self, path: Path) -> None: ...
    def delete_branch(self, branch: str) -> None: ...
    def prune_worktrees(self) -> None: ...
    def rebase(self, worktree: Path, onto: str) -> RebaseResult: ...
    def current_branch(self) -> str: ...
    def resolve_ref(self, ref: str) -> str: ...
    def diff_for_review(self, worktree: Path, base_oid: str) -> str: ...
    def compare_and_swap_ref(self, ref: str, expected_oid: str, new_oid: str) -> None: ...
    def squash_and_commit(self, worktree: Path, onto: str, msg: str) -> bool: ...
    def fast_forward(self, branch: str) -> None: ...
    def untracked_merge_collisions(self, worktree: Path) -> tuple[str, ...]: ...


class GraphReadPort(Protocol):
    def get_node(self, node_id: int) -> MikadoNode | None: ...
    def get_children(self, node_id: int) -> list[MikadoNode]: ...
    def get_file_ownership(self, node_id: int) -> list[str]: ...
    def get_execution_snapshot(self, node_ids: list[int]) -> GraphExecutionSnapshot: ...


class CrgPort(Protocol):
    def ensure_graph(self, project_root: Path) -> None: ...
    def get_impact_radius(self, files: list[str]) -> dict[str, object]: ...
    def get_architecture_overview(self) -> dict[str, object]: ...
    def list_communities(
        self,
        sort_by: str = "size",
        min_size: int = 0,
    ) -> list[dict[str, object]]: ...
    def list_flows(
        self,
        sort_by: str = "criticality",
        limit: int = 50,
    ) -> list[dict[str, object]]: ...
    def get_bridge_nodes(self, top_n: int = 10) -> list[dict[str, object]]: ...
    def get_hub_nodes(self, top_n: int = 10) -> list[dict[str, object]]: ...


class CommandResult(Protocol):
    returncode: int
    stdout: str
    stderr: str


class ToolchainPort(Protocol):
    def find_executable(self, command: str) -> str | None: ...
    def run(self, argv: list[str], *, check: bool = False) -> CommandResult: ...
    def system(self) -> str: ...
    def machine(self) -> str: ...
    def environment(self, name: str) -> str | None: ...
    def home(self) -> Path: ...


TerminalRunOutcome = Literal["completed", "stopped", "failed"]


class RunStateView(Protocol):
    """Run state fields exposed to orchestration consumers."""

    @property
    def run_id(self) -> str: ...
    @property
    def status(self) -> Enum: ...
    @property
    def total(self) -> int: ...
    @property
    def stop_requested(self) -> bool: ...
    @property
    def force_stop_requested(self) -> bool: ...


class ReviewResult(Protocol):
    """Adversarial review verdict returned by a loop port."""

    @property
    def approved(self) -> bool: ...
    @property
    def findings_md(self) -> str: ...


class RunHandle(Protocol):
    """Handle returned by a loop port for run inspection."""

    @property
    def state(self) -> RunStateView: ...


class LoopPort(Protocol):
    def create_run(
        self,
        agent: str,
        ralph_dir: Path,
        ralph_file: Path,
        quality_gates: tuple[Gate, ...] | None,
        project_root: Path | None = None,
        commit_footer: str | None = None,
        base_oid: str | None = None,
        runtime_policy: object | None = None,
        run_id: str | None = None,
        completion_probe: Callable[[], bool] | None = None,
    ) -> RunHandle: ...
    def start_run(self, run_id: str) -> None: ...
    def queue_guidance(self, run_id: str, text: str) -> bool: ...
    def request_stop_run(self, run_id: str) -> None: ...
    def stop_run(self, run_id: str, timeout: float | None = None) -> bool: ...
    def force_stop_run(self, run_id: str, timeout: float | None = None) -> bool: ...
    def list_runs(self) -> Sequence[RunHandle]: ...
    def get_run(self, run_id: str) -> RunHandle | None: ...
    def is_run_alive(self, run_id: str) -> bool: ...
    def get_run_stdout(self, run_id: str) -> list[str]: ...
    def get_run_failure_detail(self, run_id: str) -> str | None: ...
    def get_run_output_tail(self, run_id: str, max_lines: int) -> list[str]: ...
    def get_run_guidance(self, run_id: str) -> tuple[str, ...]: ...
    def wait_for_next_completion(
        self,
        active_run_ids: set[str],
        timeout: float | None = None,
    ) -> tuple[str, TerminalRunOutcome | ProgressEvent]: ...
    def run_node_review(
        self,
        agent: str,
        prompt: str,
        worktree: Path,
        project_root: Path,
    ) -> ReviewResult: ...
    def verify_spec(
        self,
        spec_text: str,
        graph_state: str,
    ) -> VerifySpecResult: ...
    def generate_ralph_md(
        self,
        brief: str,
        quality_gates: tuple[Gate, ...] | None,
        output_path: Path,
        prior_findings: str = "",
        findings_round: int | None = None,
    ) -> Path: ...
