"""Per-harness agent-def renderers and the sync driver."""

from __future__ import annotations

import os
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import tomli_w
import yaml

from milknado.domains.config_sync._identity import (
    FlavorIdentity,
    RenderedDef,
    _has_bash,
    resolve_flavor_identity,
)

if TYPE_CHECKING:
    from milknado.domains.common.config import MilknadoConfig
    from milknado.domains.common.types import TaskFlavor

_GENERATED = "# GENERATED by milknado config sync — do not edit"


@dataclass(frozen=True)
class SyncFilter:
    """Pair of (harnesses, flavors) for sync() to keep params ≤4."""

    harnesses: list[str]
    flavors: list[TaskFlavor]


def render_claude(identity: FlavorIdentity, agents_dir: Path) -> RenderedDef:
    """Render a Claude Code agent-def (YAML frontmatter) for this flavor.

    When identity.user_controlled_tools is True (full-custom execution_agent with no
    tools override), the tools: line is omitted — the user controls tool access entirely.
    """
    flavor = identity.flavor.value
    fields: dict[str, object] = {
        "name": f"milknado-worker-{flavor}",
        "description": f"milknado {flavor} worker",
        "model": identity.model,
    }
    if not identity.user_controlled_tools:
        fields["tools"] = ", ".join(identity.tools)
    fields["maxTurns"] = identity.max_turns
    content = f"---\n{_GENERATED}\n{yaml.dump(fields, sort_keys=False, allow_unicode=True)}---\n"
    return RenderedDef(
        harness="claude",
        path=agents_dir / f"milknado-worker-{flavor}.md",
        content=content,
    )


def render_opencode(identity: FlavorIdentity, agents_dir: Path) -> RenderedDef:
    """Render an opencode agent-def (YAML frontmatter, capability projection)."""
    flavor = identity.flavor.value
    edit_perm = "allow" if identity.is_write_capable else "deny"
    bash_perm = "allow" if _has_bash(identity.tools) else "deny"
    fields: dict[str, object] = {
        "name": f"milknado-worker-{flavor}",
        "description": f"milknado {flavor} worker",
        "model": identity.model,
        "permission": {
            "edit": edit_perm,
            "write": edit_perm,
            "bash": bash_perm,
        },
    }
    content = f"---\n{_GENERATED}\n{yaml.dump(fields, sort_keys=False, allow_unicode=True)}---\n"
    return RenderedDef(
        harness="opencode",
        path=agents_dir / f"milknado-worker-{flavor}.md",
        content=content,
    )


def render_codex(identity: FlavorIdentity, agents_dir: Path) -> RenderedDef:
    """Render a Codex TOML agent-def (coarse sandbox projection) for this flavor."""
    flavor = identity.flavor.value
    sandbox = "workspace-write" if identity.is_write_capable else "read-only"
    fields = {
        "name": f"milknado-worker-{flavor}",
        "description": f"milknado {flavor} worker",
        "developer_instructions": (
            f"milknado {flavor} worker — act on the task brief supplied at dispatch."
        ),
        "sandbox_mode": sandbox,
    }
    content = f"{_GENERATED}\n{tomli_w.dumps(fields)}"
    return RenderedDef(
        harness="codex",
        path=agents_dir / f"milknado-worker-{flavor}.toml",
        content=content,
    )


_RENDER_FNS: dict[str, Callable[[FlavorIdentity, Path], RenderedDef]] = {
    "claude": render_claude,
    "opencode": render_opencode,
    "codex": render_codex,
}


def _render_flavor(
    identity: FlavorIdentity, harnesses: list[str], dirs: dict[str, Path], dry_run: bool
) -> list[RenderedDef]:
    """Render and optionally write defs for one flavor across all requested harnesses."""
    results: list[RenderedDef] = []
    for harness in harnesses:
        if harness not in _RENDER_FNS:
            raise ValueError(f"unknown harness: {harness!r}")
        rd = _RENDER_FNS[harness](identity, dirs[harness])
        results.append(rd)
        if not dry_run:
            rd.path.parent.mkdir(parents=True, exist_ok=True)
            rd.path.write_text(rd.content, encoding="utf-8")
    return results


def sync(cfg: MilknadoConfig, scope: str, filt: SyncFilter, dry_run: bool) -> list[RenderedDef]:
    """Render and optionally write agent-def files for all requested flavor×harness pairs.

    Returns the full manifest regardless of dry_run; writes files only when dry_run=False.
    File paths follow milknado-worker-<flavor>.{md,toml} — the only names this function
    ever writes, which enforces the file-prefix guard (user files are never touched).
    """
    dirs = _compute_dirs(cfg, scope)
    results: list[RenderedDef] = []
    for flavor in filt.flavors:
        identity = resolve_flavor_identity(cfg, flavor)
        results.extend(_render_flavor(identity, filt.harnesses, dirs, dry_run))
    return results


def _compute_dirs(cfg: MilknadoConfig, scope: str) -> dict[str, Path]:
    """Return per-harness agent directories for the given scope."""
    if scope == "global":
        home = Path.home()
        xdg = os.environ.get("XDG_CONFIG_HOME", "").strip() or str(home / ".config")
        return {
            "claude": home / ".claude" / "agents",
            "opencode": Path(xdg).resolve() / "opencode" / "agents",
            "codex": home / ".codex" / "agents",
        }
    root = cfg.project_root
    return {
        "claude": root / ".claude" / "agents",
        "opencode": root / ".opencode" / "agents",
        "codex": root / ".codex" / "agents",
    }
